# Generated by Django 5.0.6 on 2024-06-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_category_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learn.category'),
        ),
    ]
